#ifndef COLLECT_VIEW_RFA1_H
#define COLLECT_VIEW_RFA1_H

#include "collect-view.h"

enum {
  BATTERY_VOLTAGE_SENSOR,
  BATTERY_INDICATOR,
  LIGHT1_SENSOR,
  LIGHT2_SENSOR,
  TEMP_SENSOR,
  HUMIDIT_SENSOR,
  RSSI_SENSOR,
  ETX1_SENSOR,
  ETX2_SENSOR,
  ETX3_SENSOR,
  ETX4_SENSOR,
};


#endif /* COLLECT_VIEW_RFA1_H */
